{
  "openapi":"3.0.2",
  "info": {
    "title":"NLW Valoriza",
    "version":"1.0",
    "license": {
      "name": "MIT",
      "url": "https://github.com/DiegoVictor/nlw-valoriza/blob/main/LICENSE"
    }
  },
  "servers": [
    {
      "url":"https://localhost:3000/v1"
    }
  ],
  "paths": {
    "/sessions": {
      "post": {
        "tags": ["sessions"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email", "password"
                ],
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "johndoe@example.com",
                "password": "123456"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Return an access token",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "access_token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE2Mjg2MzkxNDQsImV4cCI6MTYyODY0MDA0NCwic3ViIjoiNzNhZDU5NjYtZWYxOC00OWRkLWJjNzYtNDRiYmMzZDY4MDdmIn0.GzUh2OW7euhS8usCcerm1z6eYZSobG4gbsfI2mQv1kU"
                }
              }
            }
          },
          "400": {
            "description": "Email and/or password is incorret",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "examples": {
                  "440": {
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "Email and/or password is incorret",
                      "code": 440,
                      "docs": "https://github.com/DiegoVictor/nlw-valoriza#errors-reference"
                    }
                  },
                  "441": {
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "Email and/or password is incorret",
                      "code": 441,
                      "docs": "https://github.com/DiegoVictor/nlw-valoriza#errors-reference"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": ["users"],
        "security": [{
          "bearer": []
        }],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Return users list",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/User"
                  }
                },
                "examples": {
                  "Users": {
                    "$ref": "#/components/examples/Users"
                  }
                }
              }
            },
            "headers": {
              "X-Total-Count": {
                "description": "Total number of registries in the database",
                "schema": {
                  "type": "integer"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name", "email", "password"
                ],
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "admin": {
                    "type": "boolean"
                  }
                }
              },
              "example": {
                "name": "John Doe",
                "email": "johndoe@example.com",
                "password": "123456",
                "admin": true
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Return the created user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "User": {
                    "$ref": "#/components/examples/User"
                  }
                }
              }
            }
          },
          "400": {
            "description": "User already exists",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 400,
                  "error": "Bad Request",
                  "message": "User already exists",
                  "code": 140,
                  "docs": "https://github.com/DiegoVictor/nlw-valoriza#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/tags": {
      "get": {
        "tags": ["tags"],
        "security": [{
          "bearer": []
        }],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Return tags",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Tag"
                  }
                },
                "examples": {
                  "Tags": {
                    "$ref": "#/components/examples/Tags"
                  }
                }
              }
            },
            "headers": {
              "X-Total-Count": {
                "description": "Total number of registries in the database",
                "schema": {
                  "type": "integer"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["tags"],
        "security": [{
          "bearer": []
        }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name"
                ],
                "properties": {
                  "name": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "inspiring"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Create a new tag",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Tag"
                },
                "examples": {
                  "Tag": {
                    "$ref": "#/components/examples/Tag"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Tag already exists",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 400,
                  "error": "Bad Request",
                  "message": "Tag already exists",
                  "code": 240,
                  "docs": "https://github.com/DiegoVictor/nlw-valoriza#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/compliments": {
      "post": {
        "tags": ["compliments"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "tag_id": {
                    "type": "string"
                  },
                  "receiver_id": {
                    "type": "string"
                  },
                  "message": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "tag_id": "8bec8765-868d-45ba-b717-5e191e566e29",
                "receiver_id": "fe6a1d7e-af78-474d-8657-74cdcdd3e90c",
                "message": "Lorem ipsum dolor sit amet"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Send compliment to another user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Compliment"
                },
                "example": {
                  "id": "6b9d3229-ebf6-4166-9edb-435ca92d250b",
                  "sender_id": "73ad5966-ef18-49dd-bc76-44bbc3d6807f",
                  "receiver_id": "fe6a1d7e-af78-474d-8657-74cdcdd3e90c",
                  "tag_id": "8bec8765-868d-45ba-b717-5e191e566e29",
                  "message": "Lorem ipsum dolor sit amet",
                  "created_at": "2021-08-11T22:31:19.000Z"
                }
              }
            }
          },
          "400": {
            "description": "Is not allowed create a compliment from and to the same user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 400,
                  "error": "Bad Request",
                  "message": "Is not allowed create a compliment from and to the same user",
                  "code": 340,
                  "docs": "https://github.com/DiegoVictor/nlw-valoriza#errors-reference"
                }
              }
            }
          },
          "404": {
            "description": "Receiver user not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "Receiver user not found",
                  "code": 344,
                  "docs": "https://github.com/DiegoVictor/nlw-valoriza#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/compliments/sent": {
      "get": {
        "tags": ["compliments"],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Return compliemnts sent",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "message": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string"
                      },
                      "receiver": {
                        "$ref": "#/components/schemas/User"
                      },
                      "sender": {
                        "$ref": "#/components/schemas/User"
                      },
                      "tag": {
                        "$ref": "#/components/schemas/Tag"
                      }
                    },
                  }
                },
                "example": [
                  {
                    "id": "6b9d3229-ebf6-4166-9edb-435ca92d250b",
                    "message": "Lorem ipsum dolor sit amet",
                    "created_at": "2021-08-11T22:31:19.000Z",
                    "receiver": {
                      "id": "fe6a1d7e-af78-474d-8657-74cdcdd3e90c",
                      "name": "John Doe2",
                      "email": "johndoe2@example.com",
                      "admin": true,
                      "created_at": "2021-08-11T22:31:07.000Z",
                      "updated_at": "2021-08-11T22:31:07.000Z"
                    },
                    "sender": {
                      "id": "73ad5966-ef18-49dd-bc76-44bbc3d6807f",
                      "name": "John Doe",
                      "email": "johndoe@example.com",
                      "admin": true,
                      "created_at": "2021-08-10T23:45:40.000Z",
                      "updated_at": "2021-08-10T23:45:40.000Z"
                    },
                    "tag": {
                      "id": "8bec8765-868d-45ba-b717-5e191e566e29",
                      "name": "inspiring",
                      "created_at": "2021-08-11T22:00:28.000Z",
                      "updated_at": "2021-08-11T22:00:28.000Z",
                      "label": "#inspiring"
                    }
                  }
                ]
              }
            },
            "headers": {
              "X-Total-Count": {
                "description": "Total number of registries in the database",
                "schema": {
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    },
    "/compliments/received": {
      "get": {
        "tags": ["compliments"],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Return compliemnts received",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "message": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string"
                      },
                      "receiver": {
                        "$ref": "#/components/schemas/User"
                      },
                      "sender": {
                        "$ref": "#/components/schemas/User"
                      },
                      "tag": {
                        "$ref": "#/components/schemas/Tag"
                      }
                    },
                  }
                },
                "example": [
                  {
                    "id": "6b9d3229-ebf6-4166-9edb-435ca92d250b",
                    "message": "Lorem ipsum dolor sit amet",
                    "created_at": "2021-08-11T22:31:19.000Z",
                    "receiver": {
                      "id": "fe6a1d7e-af78-474d-8657-74cdcdd3e90c",
                      "name": "John Doe2",
                      "email": "johndoe2@example.com",
                      "admin": true,
                      "created_at": "2021-08-11T22:31:07.000Z",
                      "updated_at": "2021-08-11T22:31:07.000Z"
                    },
                    "sender": {
                      "id": "73ad5966-ef18-49dd-bc76-44bbc3d6807f",
                      "name": "John Doe",
                      "email": "johndoe@example.com",
                      "admin": true,
                      "created_at": "2021-08-10T23:45:40.000Z",
                      "updated_at": "2021-08-10T23:45:40.000Z"
                    },
                    "tag": {
                      "id": "8bec8765-868d-45ba-b717-5e191e566e29",
                      "name": "inspiring",
                      "created_at": "2021-08-11T22:00:28.000Z",
                      "updated_at": "2021-08-11T22:00:28.000Z",
                      "label": "#inspiring"
                    }
                  }
                ]
              }
            },
            "headers": {
              "X-Total-Count": {
                "description": "Total number of registries in the database",
                "schema": {
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string",
          },
          "admin": {
            "type": "boolean"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Tag": {
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "label": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Compliment": {
        "properties": {
          "id": {
            "type": "string"
          },
          "sender_id": {
            "type": "string"
          },
          "receiver_id": {
            "type": "string"
          },
          "tag_id": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          }
        }
      },
      "Error": {
        "properties": {
          "statusCode": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "code": {
            "type": "integer"
          },
          "docs": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "examples": {
      "User": {
        "value": {
          "id": "73ad5966-ef18-49dd-bc76-44bbc3d6807f",
          "name": "John Doe",
          "email": "johndoe@example.com",
          "admin": true,
          "created_at": "2021-08-10T23:45:40.000Z",
          "updated_at": "2021-08-10T23:45:40.000Z"
        }
      },
      "Users": {
        "value": [{
          "id": "73ad5966-ef18-49dd-bc76-44bbc3d6807f",
          "name": "John Doe",
          "email": "johndoe@example.com",
          "admin": true,
          "created_at": "2021-08-10T23:45:40.000Z",
          "updated_at": "2021-08-10T23:45:40.000Z"
        }]
      },
      "Tag": {
        "value": {
          "id": "8bec8765-868d-45ba-b717-5e191e566e29",
          "name": "inspiring",
          "label": "#inspiring",
          "created_at": "2021-08-11T22:00:28.000Z",
          "updated_at": "2021-08-11T22:00:28.000Z"
        }
      },
      "Tags": {
        "value": [{
          "id": "8bec8765-868d-45ba-b717-5e191e566e29",
          "name": "inspiring",
          "created_at": "2021-08-11T22:00:28.000Z",
          "updated_at": "2021-08-11T22:00:28.000Z"
        }]
      }
    }
  }
}
